export interface Web2Platform {
  id: string;
  name: string;
  da: number;
  type: string;
  url: string;
}

export const WEB2_PLATFORMS: Web2Platform[] = [
  { id: 'wp', name: 'Wordpress.com', da: 92, type: 'DoFollow', url: 'wordpress.com' },
  { id: 'tumblr', name: 'Tumblr.com', da: 86, type: 'DoFollow', url: 'tumblr.com' },
  { id: 'blogger', name: 'Blogger.com', da: 99, type: 'DoFollow', url: 'blogger.com' },
  { id: 'jimdo', name: 'Jimdo.com', da: 75, type: 'DoFollow', url: 'jimdo.com' },
  { id: 'livejournal', name: 'Livejournal.com', da: 93, type: 'DoFollow', url: 'livejournal.com' },
  { id: 'wix', name: 'Wix.com', da: 94, type: 'DoFollow', url: 'wix.com' },
  { id: 'weebly', name: 'Weebly.com', da: 93, type: 'DoFollow', url: 'weebly.com' },
  { id: 'blogspot', name: 'Blogspot.com', da: 66, type: 'DoFollow', url: 'blogspot.com' },
  { id: 'deviantart', name: 'Deviantart.com', da: 84, type: 'DoFollow', url: 'deviantart.com' },
  { id: 'medium', name: 'Medium.com', da: 96, type: 'DoFollow', url: 'medium.com' },
  { id: 'sitesgoogle', name: 'Sites.google.com', da: 97, type: 'DoFollow', url: 'sites.google.com' },
  { id: 'evernote', name: 'Evernote.com', da: 91, type: 'DoFollow', url: 'evernote.com' },
  { id: 'quora', name: 'Quora.com', da: 93, type: 'DoFollow', url: 'quora.com' },
  { id: 'linkedin', name: 'LinkedIn', da: 98, type: 'DoFollow', url: 'linkedin.com' },
  { id: 'squarespace', name: 'Squarespace', da: 75, type: 'DoFollow', url: 'squarespace.com' },
  { id: 'wikipedia', name: 'Wikipedia.org', da: 93, type: 'DoFollow', url: 'wikipedia.org' },
  { id: 'skyrock', name: 'Skyrock.com', da: 92, type: 'DoFollow', url: 'skyrock.com' },
  { id: 'justpasteit', name: 'Justpaste.it', da: 90, type: 'DoFollow', url: 'justpaste.it' },
  { id: 'ucoz', name: 'Ucoz.com', da: 89, type: 'DoFollow', url: 'ucoz.com' },
  { id: 'minds', name: 'Minds.com', da: 88, type: 'DoFollow', url: 'minds.com' },
  { id: 'bravenet', name: 'Bravenet.com', da: 77, type: 'DoFollow', url: 'bravenet.com' },
  { id: 'penzu', name: 'Penzu.com', da: 74, type: 'DoFollow', url: 'penzu.com' },
  { id: 'snappages', name: 'SnapPages', da: 78, type: 'DoFollow', url: 'snappages.com' },
  { id: 'imcreator', name: 'IM Creator', da: 67, type: 'DoFollow', url: 'imcreator.com' },
  { id: 'mozello', name: 'Mozello', da: 79, type: 'DoFollow', url: 'mozello.com' },
  { id: 'site123', name: 'Site123', da: 71, type: 'DoFollow', url: 'site123.com' },
  { id: 'webnode', name: 'Webnode', da: 78, type: 'DoFollow', url: 'webnode.com' },
  { id: 'webstarts', name: 'Webstarts', da: 69, type: 'DoFollow', url: 'webstarts.com' },
  { id: 'weblium', name: 'Weblium', da: 71, type: 'DoFollow', url: 'weblium.com' },
  { id: 'goodnightjournal', name: 'Goodnight Journal', da: 75, type: 'DoFollow', url: 'goodnightjournal.com' },
  { id: 'shutterfly', name: 'Shutterfly', da: 71, type: 'DoFollow', url: 'shutterfly.com' },
  { id: 'apsense', name: 'APSense', da: 71, type: 'DoFollow', url: 'apsense.com' },
  { id: 'jigsy', name: 'Jigsy', da: 71, type: 'DoFollow', url: 'jigsy.com' },
  { id: 'bookmark', name: 'Bookmark.com', da: 55, type: 'DoFollow', url: 'bookmark.com' },
  { id: 'splashthat', name: 'SplashThat', da: 89, type: 'DoFollow', url: 'splashthat.com' },
  { id: 'pixieset', name: 'Pixieset', da: 65, type: 'DoFollow', url: 'pixieset.com' },
  { id: 'bigcartel', name: 'BigCartel', da: 90, type: 'DoFollow', url: 'bigcartel.com' },
  { id: 'rakuten', name: 'Rakuten', da: 93, type: 'DoFollow', url: 'rakuten.co.jp' },
  { id: 'hubpages', name: 'HubPages', da: 71, type: 'DoFollow', url: 'hubpages.com' },
  { id: 'fotki', name: 'Fotki', da: 71, type: 'DoFollow', url: 'fotki.com' },
  { id: 'wallinside', name: 'WallInside', da: 71, type: 'DoFollow', url: 'wallinside.com' },
  { id: 'ohlog', name: 'Ohlog', da: 51, type: 'DoFollow', url: 'ohlog.com' },
  { id: 'all4webs', name: 'All4Webs', da: 61, type: 'DoFollow', url: 'all4webs.com' },
  { id: 'strikingly', name: 'Strikingly', da: 84, type: 'DoFollow', url: 'strikingly.com' },
  { id: 'yola', name: 'Yola', da: 78, type: 'DoFollow', url: 'yola.com' },
  { id: 'substack', name: 'Substack', da: 91, type: 'DoFollow', url: 'substack.com' },
  { id: 'hashnode', name: 'Hashnode', da: 82, type: 'DoFollow', url: 'hashnode.com' },
  { id: 'devto', name: 'Dev.to', da: 89, type: 'DoFollow', url: 'dev.to' },
  { id: 'behance', name: 'Behance', da: 97, type: 'DoFollow', url: 'behance.net' },
  { id: 'dribbble', name: 'Dribbble', da: 92, type: 'DoFollow', url: 'dribbble.com' },
  { id: 'reddit', name: 'Reddit', da: 99, type: 'NoFollow', url: 'reddit.com' },
  { id: 'scoopit', name: 'Scoop.it', da: 85, type: 'NoFollow', url: 'scoop.it' },
  { id: 'flipboard', name: 'Flipboard', da: 91, type: 'NoFollow', url: 'flipboard.com' },
  { id: 'pinterest', name: 'Pinterest', da: 97, type: 'NoFollow', url: 'pinterest.com' },
  { id: 'myspace', name: 'MySpace', da: 94, type: 'DoFollow', url: 'myspace.com' },
  { id: 'angelfire', name: 'Angelfire', da: 82, type: 'DoFollow', url: 'angelfire.com' },
  { id: 'tripod', name: 'Tripod', da: 81, type: 'DoFollow', url: 'tripod.com' },
  { id: 'brave', name: 'Brave Journal', da: 55, type: 'DoFollow', url: 'bravejournal.com' },
  { id: 'diary', name: 'Diary.com', da: 50, type: 'DoFollow', url: 'diary.com' },
  { id: 'blogher', name: 'BlogHer', da: 84, type: 'DoFollow', url: 'blogher.com' },
  { id: 'gather', name: 'Gather', da: 65, type: 'DoFollow', url: 'gather.com' },
  { id: 'ning', name: 'Ning', da: 91, type: 'DoFollow', url: 'ning.com' },
  { id: 'soup', name: 'Soup.io', da: 78, type: 'DoFollow', url: 'soup.io' },
  { id: 'webs', name: 'Webs.com', da: 89, type: 'DoFollow', url: 'webs.com' },
  { id: 'moonfruit', name: 'Moonfruit', da: 75, type: 'DoFollow', url: 'moonfruit.com' },
  { id: 'sitey', name: 'Sitey', da: 58, type: 'DoFollow', url: 'sitey.me' },
  { id: 'puzl', name: 'Puzl.com', da: 45, type: 'DoFollow', url: 'puzl.com' },
  { id: 'carbonmade', name: 'Carbonmade', da: 88, type: 'DoFollow', url: 'carbonmade.com' },
  { id: 'clippings', name: 'Clippings.me', da: 65, type: 'DoFollow', url: 'clippings.me' },
  { id: 'contently', name: 'Contently', da: 89, type: 'DoFollow', url: 'contently.com' },
  { id: 'muckrack', name: 'Muck Rack', da: 84, type: 'DoFollow', url: 'muckrack.com' },
  { id: 'prlog', name: 'PRLog', da: 78, type: 'DoFollow', url: 'prlog.org' },
  { id: 'issuu', name: 'Issuu', da: 94, type: 'NoFollow', url: 'issuu.com' },
  { id: 'scribd', name: 'Scribd', da: 94, type: 'NoFollow', url: 'scribd.com' }
];
